version: '3.4'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookdb --quiet
      start_period: 10s

  app:
    container_name: springboot-service
    image: rolandsall24/springboot-keycloak:1.0.0
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongo

  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    ports:
      - "7000:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 30s
